spring.application.name=consumer
spring.rabbitmq.port=5672
spring.rabbitmq.host=localhost
spring.rabbitmq.username=user
spring.rabbitmq.password=password
logging.level.org.springframework.amqp=DEBUG
# Monitoring: Actuator & Prometheus
management.endpoints.web.exposure.include=prometheus,health,info,metrics
management.endpoint.prometheus.enabled=true
management.endpoint.health.enabled=true
management.endpoint.health.show-details=always
management.metrics.export.prometheus.enabled=true
